version: '3.1'

services:

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - ${PORT:-8080}:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ${DB_HOST:-localhost}
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_DATABASE}
      url: "${PROTOCOL:-http}://${SITE_URL:-localhost}:${PORT:-8080}"

  db:
    image: mysql:${MYSQL_DOCKER_VERSION:-latest}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
