version: '3.1'

services:

  ghost:
    container_name: ghost
    image: ghost:${GHOST_DOCKER_VERSION:-latest}
    restart: always
    ports:
      - ${PORT:-8080}:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ${DB_HOST:-localhost}
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_DATABASE}
      url: "${PROTOCOL:-https}://${SITE_URL:-localhost}:${PORT:-8080}"
      NODE_ENV: ${NODE_ENV:-development} # change me for production

    links:
      - mysql


  mysql:
    container_name: ghost_db_mysql
    image: mysql:${MYSQL_DOCKER_VERSION:-latest}
    restart: always
    volumes:
      - ~/data/db:/var/lib/mysql

    ports:
      - ${DB_PORT:-3306}:3306

    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD:  "${DB_PASSWORD}"