version: '3.8'

services:

# ===================================================== # 
#                       Nginx                           #
# ===================================================== # 
# See: https://github.com/gabrielberthier/docker-compose-ghost-setup
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: ghost-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/configs/ghost.template:/etc/nginx/conf.d/ghost.template
      - ./configs/nginx:/etc/nginx/conf.d/
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    depends_on:
      # - certbot
      - ghost
    restart: always
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"



# ===================================================== # 
#                       Ghost                           #
# ===================================================== # 
  ghost:
    image: ghost:${GHOST_DOCKER_VERSION}
    container_name: ghost_blog
    hostname: ghost-blog
    ports:
      - 2368:2368

    volumes:
      - ./data/content:/var/lib/ghost/content:z
      
    restart: always
    depends_on:
      - db

    environment:
      NODE_ENV: ${NODE_ENV}
      url: "${PROTOCOL}://${APP_DOMAIN}:${GHOST_PORT}"
      database__client: mysql
      database__connection__host: db  # this points to the db service container
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}

      # Backblaze settings
      # storage__active: "ghost-storage-back-blaze"
      # storage__ghost-storage-back-blaze__keyId: ${BACKBLAZE_KEY_ID}
      # storage__ghost-storage-back-blaze__secretKey: ${BACKBLAZE_SECRET}

      # R2 settings
      storage__active: ghost-cloudflare-r2
      storage__media__adapter: ghost-cloudflare-r2
      storage__media__storage_type_media: true
      storage__files__adapter: ghost-cloudflare-r2
      storage__files__storage_type_files: true

      GHOST_STORAGE_ADAPTER_R2_ENDPOINT: ${GHOST_STORAGE_ADAPTER_R2_ENDPOINT}
      GHOST_STORAGE_ADAPTER_R2_ACCESS_KEY_ID: ${GHOST_STORAGE_ADAPTER_R2_ACCESS_KEY_ID}
      GHOST_STORAGE_ADAPTER_R2_SECRET_ACCESS_KEY: ${GHOST_STORAGE_ADAPTER_R2_SECRET_ACCESS_KEY}
      GHOST_STORAGE_ADAPTER_R2_BUCKET: ${GHOST_STORAGE_ADAPTER_R2_BUCKET}
      GHOST_STORAGE_ADAPTER_R2_DOMAIN: ${GHOST_STORAGE_ADAPTER_R2_DOMAIN}

    networks:
      - ghost

# ===================================================== # 
#                      MySQL                            #
# ===================================================== # 
  db:
    container_name: ghost_db
    image: mysql:${MYSQL_DOCKER_VERSION:-latest}
    restart: always
    volumes:
      - ghost_data:/var/lib/mysql

    ports:
      - ${MYSQL_PORT:-3306}:3306

    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD:  "${MYSQL_PASSWORD}"
      
    networks:
      - ghost

# ===================================================== # 
#                      Certbot                          #
# ===================================================== # 
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  ghost:
    name: ghost_blog_network

volumes:
  ghost_data: