version: '3.8'

services:

  ghost:
    image: ghost:5
    container_name: ghost_blog
    hostname: ghost-blog
    ports:
      - ${GHOST_PORT:-8080}:2368

    volumes:
      - ./data/content:/var/lib/ghost/content:z
      
    restart: always

    environment:
      NODE_ENV: ${NODE_ENV}
      url: "${PROTOCOL}://${SITE_URL}:${GHOST_PORT}"

    networks:
      - ghost


  db:
    container_name: ghost_db
    image: mysql:${MYSQL_DOCKER_VERSION:-latest}
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql

    ports:
      - ${MYSQL_PORT:-3306}:3306

    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD:  "${MYSQL_PASSWORD}"
      
    networks:
      - ghost

networks:
  ghost:
    name: ghost_blog_network
